# Generated by Django 5.1.4 on 2024-12-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercaspay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='NGN', max_length=50),
        ),
    ]
